### ISSUE TITLE
Center align the widgets

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [peter-kimanzi/peter-kimanzi#4]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/83284294/194236273-f36db802-4a47-4c6b-a22a-13f859f3ea64.png">
You can centre align the widgets

**Comment by peter-kimanzi** [comment]
yes, just go to the code and change align to center. Currently its set to left

**Comment by Aatmaj-Zephyr** [comment]
Yeah center will look better

**Comment by iammihirsig** [comment]
@peter-kimanzi  
I already did that. 
Check out the pull request. 💫
